FROM centos

MAINTAINER mylandmarktech@gmail.com

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat
#RUN curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz

ADD  https://httpd-mirror.sergal.org/apache/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.tar.gz .
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-9.0.40/* /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
